### ISSUE TITLE
TypeError: Failed to execute 'createImageBitmap' on 'Window': The provided value is not of type '(Blob or HTMLCanvasElement or HTMLImageElement or HTMLVideoElement or ImageBitmap or ImageData or OffscreenCanvas or SVGImageElement or VideoFrame)'.

### ISSUE THREAD

**Issue by 2226174644** [nytimes/three-loader-3dtiles#11]
When I loaded a 3DTiles with images ,it logged this error.
![image](https://user-images.githubusercontent.com/51537408/143979376-a6e3a62d-e4f1-4d4b-a72d-863e6f6b2208.png)
The error is likely from here: 
![image](https://user-images.githubusercontent.com/51537408/143982762-14b0a8e7-1fae-41bc-8e0c-c09a79954282.png)
![image](https://user-images.githubusercontent.com/51537408/143982705-f1717f7e-aaa0-4479-a645-42c5bd67dec9.png)
![image](https://user-images.githubusercontent.com/51537408/143983593-47ea10e5-b83a-4e56-be92-1c433ef82062.png)
Also,I have tried to load it in Cesium, it works.
Hope for your help.

**Comment by 2226174644** [comment]
I have sent the 3DTiles to your gmail @Avnerus .Hope it can help solve the problem.

**Comment by Avnerus** [comment]
Hey there! 
Thank you for reporting this and also thank you for your email with the tiles. I will look into them shortly.
In the meantime, could you tell me what you used to create the tileset? Was it tiled on Cesium ION? It looks a bit different than the format I usually worked with. Please also specify any settings that you used to create the tileset. Thank you!
/Avner

**Comment by 2226174644** [comment]
Thanks for your reply.
For the tileset ,we used our own program to create it .And it wasn't tiled on Cesium ION . It can be loaded in the Cesium without Cesium ION.
![image](https://user-images.githubusercontent.com/51537408/144377599-42937838-4f42-4d9b-ae4c-9ab9fec64f59.png)

After tracing the source,I logged the tile in the contentLoader and compared  the example 3dtiles with mine in the  **tiles.content.gltf.image**. The Detail info :
![image](https://user-images.githubusercontent.com/51537408/144378396-a79a95a3-ebff-4559-8603-5634499ccf77.png)
It looks like the function **contentLoader** which is in the options of **Tileset3D** cann't provide the correct  'tile' ?
Is the root of the problem from loaders.gl?

**Comment by Avnerus** [comment]
Hi @2226174644, thanks again for the detailed info.
Are you able to try the current build that's in `dev`? I pushed a patch which should resolve the problem (has to do with resolvingf texture paths when they are external to the glTF). However, please use `loadersGlGltf: false`. In the next release, I am leaning toward removing the hybrid mode of processing glTFs in both loaders.gl and Three.js, as it is getting difficult to maintain.
Let me know if it works!
PS. Are you planning to open-source your custom tiler?
/Avner

**Comment by 2226174644** [comment]
yeah,I have tried your current build that's in dev and used loadersGlGltf: false. It can load these images and models with without any error. However, the final result is not very good... just like--
![image](https://user-images.githubusercontent.com/51537408/144561326-9a6f34cd-cf1b-4c0b-925b-09bb5b1d1fb8.png)
It's really confusing...Can you load the complete model there？
For open-source,I'm not sure.Because modeling is the work of other colleagues and the tiler is like an earlier versions without some functions, such as KTX2 .I'll let you know if there's any news.

**Comment by Avnerus** [comment]
Hi, I ran this quickly with debug (`debug: true` in options, and `scene.add(runtime.getTileBoxes())` ),
it seems there is mismatch between the tile's bounding volume and model's transform, something that I haven't yet come across in models tiled by Cesium ION or RealityCapture. If you can see this properly in CesiumJS, could you check how the bounding volumes appear there? It might be there is a difference in how to transformations apply in loaders.gl and CesiumJS.

![image](https://user-images.githubusercontent.com/39962/144585054-dce1e6bb-cef7-40e5-9672-60fb6a4cb493.png)

**Comment by Avnerus** [comment]
Hi, I ran this quickly with debug (`debug: true` in options, and `scene.add(runtime.getTileBoxes())` ),
it seems there is mismatch between the tile's bounding volume and model's transform, something that I haven't yet come across in models tiled by Cesium ION or RealityCapture. If you can see this properly in CesiumJS, could you check how the bounding volumes appear there? It might be there is a difference in how to transformations apply in loaders.gl and CesiumJS.

![image](https://user-images.githubusercontent.com/39962/144585054-dce1e6bb-cef7-40e5-9672-60fb6a4cb493.png)

**Comment by 2226174644** [comment]
Hi~ I used the options(debug: true) ,it likely has no Tile the you circled  in my scene? 
![image](https://user-images.githubusercontent.com/51537408/144597150-e66c4d11-7ef3-4349-ad9c-417d020b4c70.png)
About the  bounding volumes In CesiumJS：
![image](https://user-images.githubusercontent.com/51537408/144597836-aa3235f5-2fbe-4bda-a7e9-c603596502cf.png)
Excuse me for giving you so much trouble, thanks.

**Comment by Avnerus** [comment]
Got it, thank you and no worries!
I suspect there might be a problem in the way the library handles the tile transforms back to three.js, but it is specific to the way the transforms are applied in your custom tileset since the issue does not occur in tilesets from RealityCapture and Cesium ION.
It is anyway in the roadmap to re-visit the transform logic, so hopefully this could be fixed soon.
In the meantime I could ask you to run a few more tests: 
1. Have you tried loading the 3d tiles using deck.gl?
2. Is it possible that you could reset the transforms/geo-locations in your tiler?

Thanks!

**Comment by 2226174644** [comment]
Because I've never used deck.gl ,It took me some time to learn it  but couldn't  load the 3dtiles in the end.I also tried using [mapbox-3dtiles](https://github.com/Geodan/mapbox-3dtiles) to load and log it,it could be loaded without error,but there is nothing at the same latitude and longitude as cesium (sorry...).
And because the 3dtiles are transformed from real scenes,so I can't reset the transforms At this stage.I can gmail another part of the whole data . May it can help you?
PS. According to my colleague, the 3dtiles is handled according to the cesium 3dtiles standard, and no special content is added .The coordinate system of the 3dtiles is the standard ellipsoidal coordinate system of ENU (The ellipsoidal coordinate system of cesium). It used to be mainly used Cesium for UE to Parse. Also it can be parsed by CesiumJS as we can see.

**Comment by 2226174644** [comment]
Fantastic! It also works very well here with me.
![image](https://user-images.githubusercontent.com/51537408/144959770-e4c1139a-bd86-493c-8bf4-84b8edb08aeb.png)
Thank you very much again for your help！

**Comment by 2226174644** [comment]
And I found another issue. if the quantity of child node is more than 2 in the tileset.json(Combination of the first two models),for example:
![image](https://user-images.githubusercontent.com/51537408/144992358-ca9f72d1-0cd8-44b0-ac9e-02340e12433f.png)
there seems to be something wrong with its texture mapping and boundingVolume.Just like:
![Snipaste_2021-12-07_15-53-08](https://user-images.githubusercontent.com/51537408/144993078-bf6406dd-5cfc-4928-ae28-34e889f217b4.png)
![image](https://user-images.githubusercontent.com/51537408/144993040-7c459280-8c68-4a8e-a0c9-909a811f5e57.png)
I will email the new file which contains the two-part model so that you can have a try. Thanxs!

**Comment by Avnerus** [comment]
Hi @2226174644,
Yes I see there is another issue here. So far I have worked only with tilesets that have just one transformation matrix at the top (root or first child), and then everything under that is in relation to that. I will look into this further and let you know.

**Comment by Avnerus** [comment]
@2226174644 I have been doing some work with handling tile transforms and tried also to support your case. Could you please try the recent version? Thanks.

**Comment by 2226174644** [comment]
Excellent! It works very well.Thank you very mush!

**Comment by Avnerus** [comment]
Great! Regarding `math.gl assertion`, it occurs when the camera has some invalid data. Might be a race condition when the update occurs before the camera object has all of its properties. I opened a separate issue for that, so I am now closing this one. Thank you for the cooperation and please let us know if you get a chance to open-source some of your work, or are interested to in contributing new features to the loader!
