### ISSUE TITLE
A little question about 'TILE SELECTED BUT NOT LOADED!!'

### ISSUE THREAD

**Issue by 2226174644** [nytimes/three-loader-3dtiles#15]
Hello！I've been learning your code recently.And  I noticed the code in the **tilesetUpdate**：
![image](https://user-images.githubusercontent.com/51537408/148037881-4584137e-7f82-4932-a9d1-05ec88bc39a9.png)
I have never encountered this error，But I wonder why.
Both the **contentLoader** and the **createGLTFNodes** are Asynchronous function,But the **tilesetUpdate** is not async.
When running to

> if (tile.selected) {
if (!renderMap[tile.id]) {

It's very likely to meet the error 'TILE SELECTED BUT NOT LOADED!!'. However,Its current performance is good actually.
I'm so curious.Hope you can guide me if you are free.Thanks!

**Comment by Avnerus** [comment]
Hey!
So on the loaders.gl side, a tile is [not selected unless its content is loaded](https://github.com/visgl/loaders.gl/blob/6465d910e88fc902ebcf73b3bce4fccf23ffb174/modules/tiles/src/tileset/traversers/tileset-traverser.ts#L285), and a tile does not mark its content as 'ready' [until the external async function (in our case using three js) is done, ](https://github.com/visgl/loaders.gl/blob/6465d910e88fc902ebcf73b3bce4fccf23ffb174/modules/tiles/src/tileset/tile-3d.ts#L393-L403). 
So this error should not appear.  Does it happen to you always for the same tile? There might be some race condition in which a tile is unloaded while it is still selected, perhaps if it was unloaded by external code.

**Comment by 2226174644** [comment]
I see.Thank you for your so quick reply!
By the way,there is another little question :
[Here, unloadQueue is used to contain the tiles that need to be unloaded](https://github.com/nytimes/three-loader-3dtiles/blob/5b452d8b895d87c0135d9525fd8e855feabb574f/src/index.ts#L190-L192);
[And we dispose the tiles in the tilesetUpdate.](https://github.com/nytimes/three-loader-3dtiles/blob/5b452d8b895d87c0135d9525fd8e855feabb574f/src/index.ts#L325-L337)
In this case,the gltfNode can't be disposed immediately. I wonder why not delete the gltfNode directly when the **onTileUnload** callback but put it in the next tilesetupdate？

**Comment by Avnerus** [comment]
I found this method to be the most reliable, ensuring that no race condition occurs in which a tile is unloaded while it is still being processed. However, it has been a while since that code was written and it might be that directly disposing the tile would work fine. If you would like to try it and see if it improves performance reliably then I am happy to accept a PR for this.
Thank you!

**Comment by 2226174644** [comment]
Make sense!
And I have tried to dispose gltfNode in the **onTileUnload**.There is no error about  race condition occurs at present.Also ,I don't feel any significant improvement in performance for the time being.
All in all ,I think your approach is reasonable and safer. Thank you for taking the time to guide me！

**Comment by Avnerus** [comment]
OK, great! 
Thank you for the feedback.
I will close this issue for now, but feel free to re-open or propose a PR if you mange to get some improvement.
