### ISSUE TITLE
A 3D tile failed to load: undefined error parsing gltf

### ISSUE THREAD

**Issue by sau0409** [nytimes/three-loader-3dtiles#162]
Hi,

I am getting this error 

A 3D tile failed to load: undefined error parsing gltf in tile TypeError: Cannot read properties of null (reading 'userData')
_onTileLoadError @ three-loader-3dtiles.js?v=da8a407f:6181
_loadTile @ three-loader-3dtiles.js?v=da8a407f:6173
await in _loadTile (async)
_loadTiles @ three-loader-3dtiles.js?v=da8a407f:6077
_updateTiles @ three-loader-3dtiles.js?v=da8a407f:6066
_onTraversalEnd @ three-loader-3dtiles.js?v=da8a407f:6055
executeTraversal @ three-loader-3dtiles.js?v=da8a407f:5445
traverse @ three-loader-3dtiles.js?v=da8a407f:5430
Le @ three-loader-3dtiles.js?v=da8a407f:12245
update @ three-loader-3dtiles.js?v=da8a407f:12336
animate @ ThreeDViewer.vue:151
requestAnimationFrame (async)
animate @ ThreeDViewer.vue:144
requestAnimationFrame (async)
animate @ ThreeDViewer.vue:144
requestAnimationFrame (async)
animate @ ThreeDViewer.vue:144
requestAnimationFrame (async)
animate @ ThreeDViewer.vue:144
requestAnimationFrame (async)
animate @ ThreeDViewer.vue:144
requestAnimationFrame (async)
animate @ ThreeDViewer.vue:144
requestAnimationFrame (async)
animate @ ThreeDViewer.vue:144
requestAnimationFrame (async)
animate @ ThreeDViewer.vue:144
requestAnimationFrame (async)
animate @ ThreeDViewer.vue:144
requestAnimationFrame (async)
animate @ ThreeDViewer.vue:144
requestAnimationFrame (async)
animate @ ThreeDViewer.vue:144
requestAnimationFrame (async)
animate @ ThreeDViewer.vue:144
(anonymous) @ ThreeDViewer.vue:159
(anonymous) @ chunk-RQPU2HK5.js?v=da8a407f:9233
callWithErrorHandling @ chunk-RQPU2HK5.js?v=da8a407f:1865
callWithAsyncErrorHandling @ chunk-RQPU2HK5.js?v=da8a407f:1872
hook.__weh.hook.__weh @ chunk-RQPU2HK5.js?v=da8a407f:4025
flushPostFlushCbs @ chunk-RQPU2HK5.js?v=da8a407f:2029
flushJobs @ chunk-RQPU2HK5.js?v=da8a407f:2056
Promise.then (async)
queueFlush @ chunk-RQPU2HK5.js?v=da8a407f:1970
queueJob @ chunk-RQPU2HK5.js?v=da8a407f:1964
scheduler @ chunk-RQPU2HK5.js?v=da8a407f:3463
resetScheduling @ chunk-RQPU2HK5.js?v=da8a407f:640
triggerEffects @ chunk-RQPU2HK5.js?v=da8a407f:683
triggerRefValue @ chunk-RQPU2HK5.js?v=da8a407f:1221
set value @ chunk-RQPU2HK5.js?v=da8a407f:1672
set @ chunk-RQPU2HK5.js?v=da8a407f:1511
changeMapMode @ ProjectMap.vue:545
await in changeMapMode (async)
callWithErrorHandling @ chunk-RQPU2HK5.js?v=da8a407f:1865
callWithAsyncErrorHandling @ chunk-RQPU2HK5.js?v=da8a407f:1872
emit @ chunk-RQPU2HK5.js?v=da8a407f:2328
(anonymous) @ chunk-RQPU2HK5.js?v=da8a407f:8354
changeActiveBtnStates @ MapModeBtnGroup.vue:241
btnClicked @ MapModeBtnGroup.vue:197
_createElementVNode.onClick._cache.<computed>._cache.<computed> @ MapModeBtnGroup.vue:95
callWithErrorHandling @ chunk-RQPU2HK5.js?v=da8a407f:1865
callWithAsyncErrorHandling @ chunk-RQPU2HK5.js?v=da8a407f:1872
invoker @ chunk-RQPU2HK5.js?v=da8a407f:10558
Show 30 more frames
Show less

**Comment by FengFengmomo** [comment]
i got this error too! i think that it's due to THREE.GLTFLoader: Unknown extension "KHR_technique_webgl".
