### ISSUE TITLE
Missing distribution file

### ISSUE THREAD

**Issue by ShammyLevva** [nytimes/three-loader-3dtiles#167]
Install instructions says

1. ES Module
Download [dist/three-loader-3dtiles.esm.min.js](https://github.com/nytimes/three-loader-3dtiles/blob/dev/dist/three-loader-3dtiles.esm.min.js) and use an importmap to import the dependencies. See [here](https://github.com/nytimes/three-loader-3dtiles/blob/dev/examples/installation/es-module) for a full example.

However I get a 404 error when visiting that folder. Indeed the entire dist folder is missing from all the branches.

**Comment by Avnerus** [comment]
Thank you for pointing this out!
Indeed, the distribution files are not anymore included in the repository, only in the published NPM.
I updated the example and README.
Closing this for now but feel free to reopen if needed.
