### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'elements')

### ISSUE THREAD

**Issue by SergeiK-27** [nytimes/three-loader-3dtiles#176]
When adding loader component to r3f app, this error is thrown and nothing is rendered. It also happens when building page from examples/r3f 
![image](https://github.com/user-attachments/assets/833663ea-5fde-489a-b0bd-daf5135a8888)

**Comment by hecodeit** [comment]
@SergeiK-27 Meeting the same error, how do you fix it?
