### ISSUE TITLE
rendering dark material, not like unlit texture 

### ISSUE THREAD

**Issue by Eytanm** [nytimes/three-loader-3dtiles#32]
Loading a model via cesium, but the model renders with dark materials, and not the original unlit textures....
what is going on there?
thank
![dark](https://user-images.githubusercontent.com/29125970/157684951-beba0289-76e4-4b40-8996-c772b2f03cbc.JPG)
s

**Comment by Avnerus** [comment]
Hi Eytan,

Since the transition to threejs r137 it seems necessary to define the renderer's output encoding:
```
import { sRGBEncoding } from 'three'
renderer.outputEncoding = sRGBEncoding;
```

The docs haven't been updated yet.
Could you try that?
Also make sure you are using the latest version 1.1.4

**Comment by Eytanm** [comment]
updated version, and works now!
thx:)
