### ISSUE TITLE
validators.js:17 Uncaught Error: Invalid number NaN

### ISSUE THREAD

**Issue by gisonjourney** [nytimes/three-loader-3dtiles#34]
<img width="613" alt="image" src="https://user-images.githubusercontent.com/31496185/159197664-7add216a-6f60-471a-8a8c-be48c8228bce.png">
hey,what about this?

**Comment by Avnerus** [comment]
Hi!
It's hard to give feedback without seeing the source data, but it appears as if something is wrong in the tile's bounding box defined in the JSON file. Could you provide the source data to check?
Thanks!

**Comment by gisonjourney** [comment]
> Hi! It's hard to give feedback without seeing the source data, but it appears as if something is wrong in the tile's bounding box defined in the JSON file. Could you provide the source data to check? Thanks!

i've already solved this problem, thank u for your reply!

**Comment by Avnerus** [comment]
Great! Closing issue.
