### ISSUE TITLE
RGBDEncoding not found in three

### ISSUE THREAD

**Issue by Albanbrice** [nytimes/three-loader-3dtiles#42]
Hello, I try to install and play with your r3f example. It appeared that some dependencies mentioned in package.json aren't up to date and lead to many warnings.

We need at least to update 'three-stdlib' to v2.8.9

thanks

https://github.com/pmndrs/three-stdlib/releases/tag/v2.8.9

**Comment by Avnerus** [comment]
This is now (finally) fixed in `dev`.
Closing issue, feel free to reopen if needed!`
