### ISSUE TITLE
Issues with RealityCapture dataset

### ISSUE THREAD

**Issue by arjan-kuiper** [nytimes/three-loader-3dtiles#49]
I'm using the RealityCapture demo which works fine out of the box. I've exported my own LoD model from RealityCapture in .b3dm, uploaded them to a webserver, and tried loading them in the viewer. Sadly, it's throwing errors and I can't seem to figure out why.

![image](https://user-images.githubusercontent.com/10105569/170380865-4c82563f-b46c-4711-a6e3-f8ae3931096b.png)

The root .json file of my own export is (coincidentally?) the same as the example one provided.
```
"asset": {
    "extras": {
        "createdWith": "RealityCapture 1.2.0.16813"
    },
    "version": "1.0"
}
```

Am I doing something wrong or is this an issue in the loader?
Just for fun, I uploaded my .b3md files to Cesium Ion, and to my surprise, it loads just fine there.

**Comment by Avnerus** [comment]
Hi @arjan-kuiper,
You're not doing anything wrong. The loader currently does not support the _gzip_-compressed tiles that are exported by RealityCapture. 
The good news is that we have a tool which not only removes the _gzip_ compression, but also optimizes the tiles with _Basis_ and _Draco_ compression. There are instructions on how to use the tool [here](https://github.com/Avnerus/3d-tiles-validator/tree/master/tools#new-command-line-tools), and also a recent discussion around the tool in [this issue](https://github.com/nytimes/three-loader-3dtiles/issues/47). Hope you are able to resolve this and feel free to ask for further assistance.

**Comment by arjan-kuiper** [comment]
Thanks @Avnerus! I've used `ungzip` to remove the gzip compression and that definitely did the trick. I still have to look into the draco compression, but I haven't figured out how to use it with a folder of .b3dm files yet.
