### ISSUE TITLE
option for point-cloud size ?

### ISSUE THREAD

**Issue by wallabyway** [nytimes/three-loader-3dtiles#56]
is there an option to change the default point size ?
https://github.com/nytimes/three-loader-3dtiles/blob/884818d2c90c762981151b820cadc3eb8ca05c1b/src/shaders.ts#L82

currently it's hard coded in the shader to 1.0 and I would like to change it to 3.0f

**Comment by Avnerus** [comment]
Hi!
Thank you for the report.
Yes, this will be fixed in the next upcoming patch, stay tuned!

**Comment by Avnerus** [comment]
This is now released in v1.1.11 via the `pointSize` option.
Closing this issue but feel free to open if needed.
