### ISSUE TITLE
Demo dependency returning 404

### ISSUE THREAD

**Issue by kfarr** [nytimes/three-loader-3dtiles#6]
Main branch demos on github pages and localhost fail to load from 404.

To reproduce, try one of these URLs in google chrome browser mac os:
http://localhost:8000/examples/demos/realitycapture/index.html (main branch; local repo after running `npm run dev`)
https://nytimes.github.io/three-loader-3dtiles/examples/demos/realitycapture/

See this console message:
```
/three-loader-3dtiles/dist/three-loader-3dtiles.esm.js:1 Failed to load resource: the server responded with a status of 404 ()
2es-module-shims.js:481 Uncaught (in promise) Error: 404  https://nytimes.github.io/three-loader-3dtiles/dist/three-loader-3dtiles.esm.js
    at es-module-shims.js:481
```

Demos do work as expected on `feature/aframe-example` branch

**Comment by Avnerus** [comment]
Thanks again @kfarr!
