### ISSUE TITLE
We tried generated 1.1 version tiles data in this viewer. but not able to load tiles data.

### ISSUE THREAD

**Issue by jayantpaliwal** [nytimes/three-loader-3dtiles#98]
We tried generated 1.1 version tiles data in this viewer. but not able to load tiles data.
our viewer and the Cesium js viewer ( with 1.1 support) are not mutually compatible as yet.

Seems the issue is the library are not able to bind {"uri":"tiles/{level}/{x}/{y}/{z}.glb"}
Below tiles.json (1.1) link attached.

`{"asset":{"version":"1.1","extras":{"ion":{"georeferenced":true,"movable":true,"terrainId":1}}},"schema":{"id":"cesium-tiling-pipeline","classes":{"tile":{"properties":{"tightBoundingBox":{"name":"Tight Bounding Box","type":"SCALAR","componentType":"FLOAT64","array":true,"count":12,"semantic":"TILE_BOUNDING_BOX"}}}}},"geometricError":20.056809047163423,"root":{"boundingVolume":{"box":[5.246493816375732,-11.81087795346204,5.281450901572764,11.579803943634033,0,0,0,11.579804266996945,0,0,0,11.579804096763194]},"geometricError":0.41705300908603965,"refine":"REPLACE","content":{"uri":"tiles/{level}/{x}/{y}/{z}.glb"},"metadata":{"class":"tile","properties":{"tightBoundingBox":[-0.7740600109100342,-11.8108777506449,-0.8566333773136567,5.559250116348267,0,0,0,11.579804064179806,0,0,0,5.4417197527099965]}},"implicitTiling":{"subdivisionScheme":"OCTREE","subtreeLevels":7,"availableLevels":7,"subtrees":{"uri":"subtrees/{level}/{x}/{y}/{z}.subtree"}},"transform":[0,1,0,0,0,0,1,0,1,0,0,0,6378163,0,0,1]}}`

Question:

Can we pass as a parameter in tiles.json for above X,Y,Z and level values to load the tiles data?
Any other alternative where we can generate the content url and subtree url as an absolute URL.
like "uri":"tiles/tiles/1/1/0.glb"} ?

**Comment by ailaohuyou-bj** [comment]
> We tried generated 1.1 version tiles data in this viewer. but not able to load tiles data. our viewer and the Cesium js viewer ( with 1.1 support) are not mutually compatible as yet.
> 
> Seems the issue is the library are not able to bind {"uri":"tiles/{level}/{x}/{y}/{z}.glb"} Below tiles.json (1.1) link attached.
> 
> `{"asset":{"version":"1.1","extras":{"ion":{"georeferenced":true,"movable":true,"terrainId":1}}},"schema":{"id":"cesium-tiling-pipeline","classes":{"tile":{"properties":{"tightBoundingBox":{"name":"Tight Bounding Box","type":"SCALAR","componentType":"FLOAT64","array":true,"count":12,"semantic":"TILE_BOUNDING_BOX"}}}}},"geometricError":20.056809047163423,"root":{"boundingVolume":{"box":[5.246493816375732,-11.81087795346204,5.281450901572764,11.579803943634033,0,0,0,11.579804266996945,0,0,0,11.579804096763194]},"geometricError":0.41705300908603965,"refine":"REPLACE","content":{"uri":"tiles/{level}/{x}/{y}/{z}.glb"},"metadata":{"class":"tile","properties":{"tightBoundingBox":[-0.7740600109100342,-11.8108777506449,-0.8566333773136567,5.559250116348267,0,0,0,11.579804064179806,0,0,0,5.4417197527099965]}},"implicitTiling":{"subdivisionScheme":"OCTREE","subtreeLevels":7,"availableLevels":7,"subtrees":{"uri":"subtrees/{level}/{x}/{y}/{z}.subtree"}},"transform":[0,1,0,0,0,0,1,0,1,0,0,0,6378163,0,0,1]}}`
> 
> Question:
> 
> Can we pass as a parameter in tiles.json for above X,Y,Z and level values to load the tiles data? Any other alternative where we can generate the content url and subtree url as an absolute URL. like "uri":"tiles/tiles/1/1/0.glb"} ?

hello Have you managed to solve your issue? I'm also encountering a problem where certain levels can't load.
